jwt:
    issuer: lomong7807@gmail.com
    secret: fJFkGp3IukK8CLXznS0Jz41WroMTkek2
logging:
    file:
        name: log/Ch11.log
    level:
        jdbc:
            connection: info
            resultsettable: info
            sqlonly: info
            sqltiming: info
        org:
            hibernate: info
            springframework:
                security: debug
        root: info
server:
    servlet:
        context-path: /
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: Kys19980!!
        url: jdbc:mysql://3.39.191.39:3306/Jboard
        username: root
    devtools:
        livereload:
            enabled: true
        restart:
            enabled: true
    jpa:
        database: mysql
        hibernate:
            ddl-auto: 'update '
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
                use_sql_comments: true
    security:
        user:
            name: user
            password: 1234
    thymeleaf:
        cache: false
        prefix: file:src/main/resources/templates/
